name: Generate snake animation

on:
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout the output branch
        uses: actions/checkout@v4
        with:
          ref: output
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Move snake to output folder
        run: |
          mkdir -p output
          mv dist/snake.svg output/snake.svg

      - name: Commit and push updated snake.svg
        run: |
          git add output/snake.svg
          git commit -m "update: snake.svg" || echo "No changes to commit"
          git push origin output
