name: Update GitHub Stats SVG

on:
  # Run the job every 6 hours
  schedule:
   #- cron: '0 */1 * * *'
    - cron: '*/10 * * * *'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GitHub stats SVG
        # NOTE: You can customize the URL with more parameters
        # Example: &theme=radical&show_icons=true&rank_icon=github
        run: |
          curl -s -o stats.svg "https://github-readme-stats.vercel.app/api?username=shoury-rana&hide_title=true&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false"

      - name: Verify SVG content
        run: |
          if ! grep -q "<svg" stats.svg; then
            echo "Error: Downloaded file is not a valid SVG."
            # We exit with 0 to prevent the workflow from failing,
            # which would send a notification. The old file remains.
            exit 0
          fi
          # If the file contains the error message, don't commit it
          if grep -q "Something went wrong" stats.svg; then
            echo "Error: Fetched SVG contains an error message."
            exit 0
          fi


      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update GitHub stats SVG"
            git push
          else
            echo "No changes to commit."
          fi
