name: Update GitHub Stats SVG

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Download GitHub stats SVG
        run: |
          curl -s -o output/stats.svg "https://github-readme-stats.vercel.app/api?username=shoury-rana&hide_title=true&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false"

      - name: Verify SVG content
        run: |
          if ! grep -q "<svg" output/stats.svg || grep -q "Something went wrong" output/stats.svg; then
            echo "Error: Downloaded file is not a valid SVG or contains an error."
            exit 0
          fi

      - name: Push stats.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
